[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn yarn:build"]

[start]
cmd = "yarn yarn:start"

[build.environment]
NODE_ENV = "production"